/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rmgoncalo_Query */

#ifndef _Included_com_rmgoncalo_Query
#define _Included_com_rmgoncalo_Query
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rmgoncalo_Query
 * Method:    updateVars
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rmgoncalo_Query_updateVars
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
