/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rmgoncalo_droidg_Daemon */

#ifndef _Included_com_rmgoncalo_droidg_Daemon
#define _Included_com_rmgoncalo_droidg_Daemon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rmgoncalo_droidg_Daemon
 * Method:    startDaemon
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rmgoncalo_droidg_Daemon_startDaemon
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
