/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rmgoncalo_droidg_LoadLibrary */

#ifndef _Included_com_rmgoncalo_droidg_LoadLibrary
#define _Included_com_rmgoncalo_droidg_LoadLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rmgoncalo_droidg_LoadLibrary
 * Method:    startDaemon
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rmgoncalo_droidg_LoadLibrary_startDaemon
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
