/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rmgoncalo_droidg_Daemon_ClientTask */

#ifndef _Included_com_rmgoncalo_droidg_Daemon_ClientTask
#define _Included_com_rmgoncalo_droidg_Daemon_ClientTask
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rmgoncalo_droidg_Daemon_ClientTask_MIN_PRIORITY
#define com_rmgoncalo_droidg_Daemon_ClientTask_MIN_PRIORITY 1L
#undef com_rmgoncalo_droidg_Daemon_ClientTask_NORM_PRIORITY
#define com_rmgoncalo_droidg_Daemon_ClientTask_NORM_PRIORITY 5L
#undef com_rmgoncalo_droidg_Daemon_ClientTask_MAX_PRIORITY
#define com_rmgoncalo_droidg_Daemon_ClientTask_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
